### PR TITLE
fix: handle pg_replication_slots/pg_stat_replication on replicas and cascading replicas

### LINKED ISSUE #547: Error "WAL control functions cannot be executed during recovery" for pg_replication_slots
**What did you do?**
Simply running exporter `0.0.1-rev (built with go1.15.8)`

**What did you expect to see?**
I expect no errors

**What did you see instead? Under which circumstances?**
```
ERROR:  recovery is in progress
HINT:  WAL control functions cannot be executed during recovery.
STATEMENT:
                                SELECT slot_name, database, active, pg_wal_lsn_diff(pg_current_wal_lsn(), restart_lsn)
                                FROM pg_replication_slots

```

**Environment**

* System information:

	insert output of `uname -srm` here
`Linux 5.4.0-66-generic x86_64`

* postgres_exporter version:

	insert output of `postgres_exporter --version` here
`postgres_exporter 0.0.1-rev (built with go1.15.8)`

* postgres_exporter flags:

```
/opt/postgres_exporter/postgres_exporter --web.listen-address=:9187 --log.level=warn --extend.query-path=/opt/postgres_exporter/queries.yaml
```

* PostgresSQL version:

	insert PostgreSQL version here
11.8

* Logs:
```
insert logs relevant to the issue here
```

While looking here
https://github.com/prometheus-community/postgres_exporter/blob/134e90888526d95c8159018c4dcb38fe526f87b7/cmd/postgres_exporter/postgres_exporter.go#L431-L443
I see no pg_is_in_recovery check

### PR DESCRIPTION
**Pull request by michael-todorovic**
Hello,
This PR aims to fix #547 where `pg_replication_slots` and `pg_stat_replication` metrics don't work well on replicas and cascading replicas (also known as standby leaders on Patroni). This allows standby clusters replication to be monitored :)

It has been tested on pg 13, 10.7 and 9.6

### CODE REVIEW

**Review by dan-aksenov — APPROVED** [review]
Seems fine to me. At least for versions ">=10.0.0"

**Comment by dan-aksenov** [comment]
Is there any chance to get review by  someone with write access?

**Comment by rockyluke** [comment]
LGTM 🚀

**Review by rockyluke — APPROVED** [review]
LGTM

**Review by mblp — APPROVED** [review]

**Comment by michael-todorovic** [comment]
@mblp I just rebased this MR, basically moving my changes to queries.go.
Could you please approve again (and hopefully merge)?

**Comment by michael-todorovic** [comment]
@mblp @SuperQ may I ask a review and hopefully an approval please? :pray:

**Comment by lbacigalgti** [comment]
Bump, can some review and merge this?

**Comment by loukoulouc** [comment]
Can some review and merge this?

**Comment by scanterog** [comment]
What are we missing to get this merged?

**Comment by michael-todorovic** [comment]
Actually there's a better change that #914 gets merged as there was more activity on that MR. This is the same exact code now :joy:

**Comment by sysadmind** [comment]
Merged via #1048

**Pull request closed without merging**
