### PR TITLE
Fix replication_slot query all supported versions

### LINKED ISSUE #495: function pg_current_wal_lsn() not exists on 9.5.x
bug in new feature in 0.9.0 
pg_replication_slots pq: function pg_current_wal_lsn() does not exist" source="postgres_exporter.go:1503"

pg_current_wal_lsn() function only exists from 10 version.

There should be a bool to switch of this new feature

### PR DESCRIPTION
**Pull request by halvaborsch**
The right way to fix #495 
Lets not forget about older postgres version.

### CODE REVIEW

**Comment by hd-deman** [comment]
@halvaborsch can you please fix DCO. Really looking forward to this MR

**Comment by halvaborsch** [comment]
@hd-deman sure sry

**Comment by hd-deman** [comment]
@SuperQ can you review pls 🙏

**Comment by AitorAcosta** [comment]
Any news on this? 
Thx

**Review by SuperQ — APPROVED** [review]
LGTM, thanks

**Comment by neuromantik33** [comment]
Great! When can we expect a new tag?

**Comment by AitorAcosta** [comment]
Thank you!

Where can I find a docker image with this fix? 
I was using this but its outdated

https://hub.docker.com/r/wrouesnel/postgres_exporter

Thx

**Comment by Siuddek** [comment]
Nice! Is there any release date for this fix?

**Comment by WalkerWalker** [comment]
is there already a release including this tag?

**Comment by WalkerWalker** [comment]
this problem still exists in version 0.12.0, postgres 9.6

log from exporter
```
ts=2023-03-27T15:32:00.188Z caller=collector.go:194 level=error msg="collector failed" name=replication_slot duration_seconds=0.011199623 err="pq: function pg_current_wal_lsn() does not exist"
```

log from postgres
```
postgres_1                        | ERROR:  function pg_current_wal_lsn() does not exist at character 25
postgres_1                        | HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
postgres_1                        | STATEMENT:  SELECT
postgres_1                        | 				slot_name,
postgres_1                        | 				pg_current_wal_lsn() - '0/0' AS current_wal_lsn,
postgres_1                        | 				coalesce(confirmed_flush_lsn, '0/0') - '0/0',
postgres_1                        | 				active
postgres_1                        | 			FROM
postgres_1                        | 				pg_replication_slots;
```

**Pull request merged**
