### PR TITLE
Bug Fix: updating ps_stat_statements query to have distinct records

### PR DESCRIPTION
**Pull request by vigneshkumar2016**
Why this update?
* The default design of pg_stat_statements doesnt have a unique key constraint to avoid duplicate entries.
* prometheus scrapper will error out complaining metrics with same value is received on query id label.

Impact Analysis:
* This way you can avoid the duplicate records from the view not being visible to prometheus scrapper.

exporter services will be happy scrapping the metrics

### CODE REVIEW

**Comment by eriktelepovsky** [comment]
Great! Looking forward to it.

**Comment by vigneshkumar2016** [comment]
> Great! Looking forward to it.

Thanks..

Note: if you are using custom prometheus code with customized labels.. then you need to change the labels accordingly in the PSQL queries.

**Comment by longtomjr** [comment]
@vigneshkumar2016 This PR drops support for earlier postgresql versions, since it uses `total_exec_time` instead of `total_time`. It looks like `pgStatStatementsQuery` is for the older PG versions, and `pgStatStatementsNewQuery` is for version 13 and up.
https://github.com/prometheus-community/postgres_exporter/blob/838f09c97f35aaabace3d04c170bd449bda0099e/collector/pg_stat_statements.go#L118-L121

**Comment by vigneshkumar2016** [comment]
> @vigneshkumar2016 This PR drops support for earlier postgresql versions, since it uses `total_exec_time` instead of `total_time`. It looks like `pgStatStatementsQuery` is for the older PG versions, and `pgStatStatementsNewQuery` is for version 13 and up.
> 
> https://github.com/prometheus-community/postgres_exporter/blob/838f09c97f35aaabace3d04c170bd449bda0099e/collector/pg_stat_statements.go#L118-L121

For Verison 13 and up the query is not similar. as you see the query. there is a change in the logic. PG13 doesn't support aggregates in where clause But PG14 does. 
If that's the case we need to revamp the whole go handler for pg_stat_statements into 3 catgory ( pgStatStatementsOldQuery , pgStatStatements13Query, pgStatStatementsNewQuery ).

Im waiting for the maintainer to reply or approve these changes.

**Comment by acharbha** [comment]
recent changes made to this PR has resolved this issue, I've the docker image built on this PR if anyone intrested, feel free to test this out.

https://hub.docker.com/r/achar007/postgres-exporter
```bash
docker pull achar007/postgres-exporter
```

**Comment by eriktelepovsky** [comment]
Hi @vigneshkumar2016 . Was the fix in this PR merged?

**Comment by vigneshkumar2016** [comment]
> Hi @vigneshkumar2016 . Was the fix in this PR merged?

Not yet I had approached the community, discussion forums and left a note to maintainer. No response. But I have them on my forked repo.

**Comment by davey** [comment]
Hi, 
would it help to poke the maintainer again? 
I'm affected by this problem too and I assume others too ...

**Comment by vigneshkumar2016** [comment]
> Can we get re-opened? The issue is still present. @vigneshkumar2016 @SuperQ

Yeah the PR says its closed with unmerged commits. so you might need to contact the maintainer.

**Comment by sysadmind** [comment]
The PR looks like it was closed by @vigneshkumar2016. Not sure if it's due to the source branch going away or something else. I am not able to merge it or reopen the PR.

**Comment by vigneshkumar2016** [comment]
Sure, will need to revise or rebase my branch.. will let you know once done..

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by elfranne** [comment]
@vigneshkumar2016 any progress on this?

**Pull request closed without merging**
