### PR TITLE
Update queries.yaml

### PR DESCRIPTION
**Pull request by ctouil**

### CODE REVIEW

**Comment by sysadmind** [comment]
It's not clear what the intent of this PR is. The queries.yaml file is being deprecated in the near future.

**Comment by benjimin** [comment]
The intent of this PR is evidently to update the syntax from postgres 12 (and older) to postgres 13+ (noting postgres 15 is current now).

https://www.postgresql.org/docs/current/pgstatstatements.html

**Comment by mcosta74** [comment]
> It's not clear what the intent of this PR is. The queries.yaml file is being deprecated in the near future.

what does it mean? are you planning to remove the ability to run extra queries?

**Comment by mcosta74** [comment]
> > what does it mean? are you planning to remove the ability to run extra queries?
> 
> Correct. We plan to remove this feature entirely as we migrate each postgres feature collector to Go code. By moving the queries into Go, we can better support multiple versions of PostgreSQL automatically. This is how it's done in the MySQL exporter and it is a far better user experience.
> 
> Most of the use of queries.yaml (business metrics, not PostgreSQL server metrics) is actually better suited for the more generic [sql_exporter](https://github.com/burningalchemist/sql_exporter).

So you're suggesting to **NOT** use custom queries but one instance of the `sql_exporter` to run business queries?

**Comment by sysadmind** [comment]
@mcosta74 That is correct.

**Comment by mcosta74** [comment]
Thanks for the info. I'm trying sql_exporter and it's exactly what I was
looking for.

==============

Massimo Costa

Il mar 9 mag 2023, 10:42 Joe Adams ***@***.***> ha scritto:

**Comment by SuperQ** [comment]
queries.yaml is now deprecated. Updates should now go into the `collector` package.

**Pull request closed without merging**
