### PR TITLE
stop logging errors on replicas, fixes #547

### LINKED ISSUE #547: Error "WAL control functions cannot be executed during recovery" for pg_replication_slots
**What did you do?**
Simply running exporter `0.0.1-rev (built with go1.15.8)`

**What did you expect to see?**
I expect no errors

**What did you see instead? Under which circumstances?**
```
ERROR:  recovery is in progress
HINT:  WAL control functions cannot be executed during recovery.
STATEMENT:
                                SELECT slot_name, database, active, pg_wal_lsn_diff(pg_current_wal_lsn(), restart_lsn)
                                FROM pg_replication_slots

```

**Environment**

* System information:

	insert output of `uname -srm` here
`Linux 5.4.0-66-generic x86_64`

* postgres_exporter version:

	insert output of `postgres_exporter --version` here
`postgres_exporter 0.0.1-rev (built with go1.15.8)`

* postgres_exporter flags:

```
/opt/postgres_exporter/postgres_exporter --web.listen-address=:9187 --log.level=warn --extend.query-path=/opt/postgres_exporter/queries.yaml
```

* PostgresSQL version:

	insert PostgreSQL version here
11.8

* Logs:
```
insert logs relevant to the issue here
```

While looking here
https://github.com/prometheus-community/postgres_exporter/blob/134e90888526d95c8159018c4dcb38fe526f87b7/cmd/postgres_exporter/postgres_exporter.go#L431-L443
I see no pg_is_in_recovery check

### PR DESCRIPTION
**Pull request by saz**
This PR tries to fix all error messages, shown on replicas, I've stumbled upon.

It's based on #914, which can be closed with the merge of this PR

### CODE REVIEW

**Comment by roock** [comment]
additionally fixes #962

**Comment by saz** [comment]
Any news on this one?

**Comment by dusatvoj** [comment]
Can someone please take a look at it? :pray: 

@sysadmind / @SuperQ / @Sticksman / ?

**Review by sysadmind — APPROVED** [review]
LGTM

**Comment by scanterog** [comment]
thanks! are you planning a new release soon?

**Comment by dusatvoj** [comment]
@sysadmind , are you able to do a release, please? 🙏 Missing this feature released

**Comment by tunbb** [comment]
> additionally fixes #962
still occurs in pg 13 and exporter 15.0

**Comment by saz** [comment]
As far as I can see, this PR is part of https://github.com/prometheus-community/postgres_exporter/releases/tag/v0.16.0

**Pull request merged**
