### PR TITLE
fix parsing include databases

### PR DESCRIPTION
**Pull request by pvanderlinden**
The introduction of the include databases flag disables the auto discovery flag completely, this PR will fix that.

### CODE REVIEW

**Review by SuperQ — APPROVED** [review]
Seems reasonable, LGTM.

**Comment by SuperQ** [comment]
Should we add some tests for this?

**Comment by pvanderlinden** [comment]
It probably should have some tests. I haven't had the time yet to check how the testing works, or how to setup some databases (as the current tests don't do that just yet).

**Comment by pvanderlinden** [comment]
@SuperQ Are there any documentation on how to run the integration tests locally? 
Also I'm wondering how usefull the include functionality is? Doesn't that actually defeat the purpose of auto discover?

**Comment by SuperQ** [comment]
Sorry, I don't know about either question. I'm not an expert in PG nor this exporter's codebase. It's an adopted project, not something from the core Prometheus team.

**Comment by pvanderlinden** [comment]
I have added a basic integration test for this, and basic instructions for running the tests. It might need improvement, but it solves the current bug and adds a very simple test for it.

**Review by SuperQ — APPROVED** [review]
LGTM, Thanks! This is great.

**Pull request merged**
