### PR TITLE
Versions in queries.yaml

### PR DESCRIPTION
**Pull request by vl4deee11**
Fix issue #502 

Added template for breaking changes

This will help users redefine the fields for their specific version without editing the project code.

### CODE REVIEW

**Comment by vl4deee11** [comment]
@SuperQ Check this PR please

**Comment by vl4deee11** [comment]
@SuperQ please check this PR =^)

**Comment by vl4deee11** [comment]
@SuperQ  can you react in any way

**Comment by SuperQ** [comment]
It's an interesting idea. I'm not sure I like how it works.

**Comment by vl4deee11** [comment]
@SuperQ Okay, don't you like it in terms of code design or in terms of performance ? In fact, it will help people to keep in the same values.yaml settings for databases of different versions

**Comment by SuperQ** [comment]
I think if we need to get more complicated than what can be done with queries.yaml, we should move the query into a dedicated collector.

**Comment by vl4deee11** [comment]
@SuperQ  okay, I'll try to do it

**Comment by SuperQ** [comment]
Thanks! I would love to see more of the queries.yaml functionality moved into code. This makes it easier for users. (This is how the MySQL exporter works)

**Comment by vl4deee11** [comment]
I looked at all the code as much as I could during my work time and also looked at mysql_exporter a little, and I did not understand a bit what you want to see with the versions, could you help a little with this?

**Comment by SuperQ** [comment]
The whole exporter needs a bit of a refactor to make it easier to add features. I know @sysadmind was interested in doing some work on this.

**Comment by vl4deee11** [comment]
Yes, I agree that this requires refactoring, but unfortunately, I cannot take responsibility for refactoring, as I am afraid that I will not have enough time (now loaded with university studies and work), but at the same time I could help with this

**Comment by sysadmind** [comment]
I did start trying to clean up the code to make a refactor easier. I opened #552 as a start. I think making sure that we have the appropriate test coverage will make sure we don't lose behavior unintentionally. I'll take a look at this pr when I get some time.

**Comment by vl4deee11** [comment]
@sysadmind Ok, thanks. I'll be happy to inject queries with versions into the new code (which I wanted to do in this PR), if you need help with refactoring, I could help (write to vl4deee11@gmail.com)!

**Comment by vl4deee11** [comment]
New https://github.com/prometheus-community/postgres_exporter/pull/553

**Pull request closed without merging**
