### PR TITLE
fix #547

### LINKED ISSUE #547: Error "WAL control functions cannot be executed during recovery" for pg_replication_slots
**What did you do?**
Simply running exporter `0.0.1-rev (built with go1.15.8)`

**What did you expect to see?**
I expect no errors

**What did you see instead? Under which circumstances?**
```
ERROR:  recovery is in progress
HINT:  WAL control functions cannot be executed during recovery.
STATEMENT:
                                SELECT slot_name, database, active, pg_wal_lsn_diff(pg_current_wal_lsn(), restart_lsn)
                                FROM pg_replication_slots

```

**Environment**

* System information:

	insert output of `uname -srm` here
`Linux 5.4.0-66-generic x86_64`

* postgres_exporter version:

	insert output of `postgres_exporter --version` here
`postgres_exporter 0.0.1-rev (built with go1.15.8)`

* postgres_exporter flags:

```
/opt/postgres_exporter/postgres_exporter --web.listen-address=:9187 --log.level=warn --extend.query-path=/opt/postgres_exporter/queries.yaml
```

* PostgresSQL version:

	insert PostgreSQL version here
11.8

* Logs:
```
insert logs relevant to the issue here
```

While looking here
https://github.com/prometheus-community/postgres_exporter/blob/134e90888526d95c8159018c4dcb38fe526f87b7/cmd/postgres_exporter/postgres_exporter.go#L431-L443
I see no pg_is_in_recovery check

### PR DESCRIPTION
**Pull request by mblp**

### CODE REVIEW

**Comment by mblp** [comment]
fix two issue #1794 and #547

**Comment by SuperQ** [comment]
This needs a DCO sign-off. You can use `git commit -s --amend` to add it.

**Comment by saz** [comment]
@mblp Are you still interested in getting your PR merged? If not, I'd like to take care of this issue

**Comment by nickaein** [comment]
@saz Does this MR fixed #547? 

This MR has been inactive for a quite while. Considering our need for a `postgres_exporter` tailored for Postgres 16, we might patch and build a custom version. If you're able to complete this MR and push it to the master branch, that would be fantastic.

**Comment by mblp** [comment]
@saz 
I'll be glad if someone takes care of it. Unfortunately, I don't have time to figure out the correct design of pull.

**Comment by saz** [comment]
@nickaein LGTM. Maybe there's a new issue introduced, but I'd rather fix the ones I'm aware of, and the PR does exactly that.

@mblp Thanks, I'll do a new PR and will mention, that it's based on your work.

**Comment by scanterog** [comment]
What are we missing to get this merged?

**Comment by SuperQ** [comment]
DCO to start.

**Comment by saz** [comment]
@SuperQ @scanterog See PR #1048

**Comment by sysadmind** [comment]
Merged via #1048

**Pull request closed without merging**
