### PR TITLE
Convert pg_stat_database to new collector model

### PR DESCRIPTION
**Pull request by sysadmind**
Signed-off-by: Joe Adams <github@joeadams.io>

### CODE REVIEW

**Comment by sysadmind** [comment]
Ping @SuperQ

**Review by SuperQ — APPROVED** [review]

**Comment by SuperQ** [comment]
CC @Sticksman

**Comment by rcrane** [comment]
It seems that all "pg_stat_database_tup_*" are not exported anymore in v0.13.0 while they are exported in v0.12.1 (tested with postgres14).
The updated [readme](https://github.com/prometheus-community/postgres_exporter#flags) states that _stat_database_ is enabled by default.
Do I have to enable something else to get these stats in v0.13 or is there something else I can try?

**Comment by Sticksman** [comment]
That's odd, they should be getting returned: https://github.com/prometheus-community/postgres_exporter/blob/master/collector/pg_stat_database.go#L389

I also see it in the dump you provided:
```
# HELP pg_stat_database_tup_deleted Number of rows deleted by queries in this database
# TYPE pg_stat_database_tup_deleted counter
pg_stat_database_tup_deleted{datid="0",datname="",server="localhost:5432"} 0
pg_stat_database_tup_deleted{datid="1",datname="template1",server="localhost:5432"} 0
pg_stat_database_tup_deleted{datid="13394",datname="template0",server="localhost:5432"} 0
pg_stat_database_tup_deleted{datid="13395",datname="postgres",server="localhost:5432"} 0
# HELP pg_stat_database_tup_fetched Number of rows fetched by queries in this database
# TYPE pg_stat_database_tup_fetched counter
pg_stat_database_tup_fetched{datid="0",datname="",server="localhost:5432"} 595
pg_stat_database_tup_fetched{datid="1",datname="template1",server="localhost:5432"} 0
pg_stat_database_tup_fetched{datid="13394",datname="template0",server="localhost:5432"} 0
pg_stat_database_tup_fetched{datid="13395",datname="postgres",server="localhost:5432"} 3555
# HELP pg_stat_database_tup_inserted Number of rows inserted by queries in this database
# TYPE pg_stat_database_tup_inserted counter
pg_stat_database_tup_inserted{datid="0",datname="",server="localhost:5432"} 2
pg_stat_database_tup_inserted{datid="1",datname="template1",server="localhost:5432"} 0
pg_stat_database_tup_inserted{datid="13394",datname="template0",server="localhost:5432"} 0
pg_stat_database_tup_inserted{datid="13395",datname="postgres",server="localhost:5432"} 0
# HELP pg_stat_database_tup_returned Number of rows returned by queries in this database
# TYPE pg_stat_database_tup_returned counter
pg_stat_database_tup_returned{datid="0",datname="",server="localhost:5432"} 1042
pg_stat_database_tup_returned{datid="1",datname="template1",server="localhost:5432"} 0
pg_stat_database_tup_returned{datid="13394",datname="template0",server="localhost:5432"} 0
pg_stat_database_tup_returned{datid="13395",datname="postgres",server="localhost:5432"} 178478
# HELP pg_stat_database_tup_updated Number of rows updated by queries in this database
# TYPE pg_stat_database_tup_updated counter
pg_stat_database_tup_updated{datid="0",datname="",server="localhost:5432"} 1
pg_stat_database_tup_updated{datid="1",datname="template1",server="localhost:5432"} 0
pg_stat_database_tup_updated{datid="13394",datname="template0",server="localhost:5432"} 0
pg_stat_database_tup_updated{datid="13395",datname="postgres",server="localhost:5432"} 0
```

**Comment by rcrane** [comment]
I guess, I could have expressed that better. The "as shown here" link was meant to show the expected output.

I attached two outputs the I took from my test using

quay.io/prometheuscommunity/postgres-exporter:v0.13.0
and
quay.io/prometheuscommunity/postgres-exporter:v0.12.1

both with postgres 14.

[metrics_13_0.txt](https://github.com/prometheus-community/postgres_exporter/files/12135846/metrics_13_0.txt)
[metrics_12_1.txt](https://github.com/prometheus-community/postgres_exporter/files/12135847/metrics_12_1.txt)

**Comment by Sticksman** [comment]
Can you check 0.13.2? I think there were some changes between 0.13.0

**Comment by algchoo** [comment]
> Can you check 0.13.2? I don't expect there to be a difference, but just so we're sure.

I ran version `0.13.2` of the exporter against PostgreSQL 15.3. I used `pgbench` to see if having something going on would help generate those metrics, but that hasn't been successful. I confirmed that using version `0.12.1` of the exporter with PostgreSQL 15.3 does provide the expected metrics.

Here's everything I'm getting for `pg_stat_database` metrics using `0.13.x`
```
# HELP pg_stat_database_conflicts_confl_bufferpin Number of queries in this database that have been canceled due to pinned buffers
# TYPE pg_stat_database_conflicts_confl_bufferpin counter
pg_stat_database_conflicts_confl_bufferpin{datid="1",datname="template1",server="localhost:5432"} 0
pg_stat_database_conflicts_confl_bufferpin{datid="16384",datname="dev",server="localhost:5432"} 0
pg_stat_database_conflicts_confl_bufferpin{datid="4",datname="template0",server="localhost:5432"} 0
pg_stat_database_conflicts_confl_bufferpin{datid="5",datname="postgres",server="localhost:5432"} 0
# HELP pg_stat_database_conflicts_confl_deadlock Number of queries in this database that have been canceled due to deadlocks
# TYPE pg_stat_database_conflicts_confl_deadlock counter
pg_stat_database_conflicts_confl_deadlock{datid="1",datname="template1",server="localhost:5432"} 0
pg_stat_database_conflicts_confl_deadlock{datid="16384",datname="dev",server="localhost:5432"} 0
1pg_stat_database_conflicts_confl_deadlock{datid="4",datname="template0",server="localhost:5432"} 0
pg_stat_database_conflicts_confl_deadlock{datid="5",datname="postgres",server="localhost:5432"} 0
# HELP pg_stat_database_conflicts_confl_lock Number of queries in this database that have been canceled due to lock timeouts
# TYPE pg_stat_database_conflicts_confl_lock counter
pg_stat_database_conflicts_confl_lock{datid="1",datname="template1",server="localhost:5432"} 0
pg_stat_database_conflicts_confl_lock{datid="16384",datname="dev",server="localhost:5432"} 0
pg_stat_database_conflicts_confl_lock{datid="4",datname="template0",server="localhost:5432"} 0
pg_stat_database_conflicts_confl_lock{datid="5",datname="postgres",server="localhost:5432"} 0
# HELP pg_stat_database_conflicts_confl_snapshot Number of queries in this database that have been canceled due to old snapshots
# TYPE pg_stat_database_conflicts_confl_snapshot counter
pg_stat_database_conflicts_confl_snapshot{datid="1",datname="template1",server="localhost:5432"} 0
pg_stat_database_conflicts_confl_snapshot{datid="16384",datname="dev",server="localhost:5432"} 0
pg_stat_database_conflicts_confl_snapshot{datid="4",datname="template0",server="localhost:5432"} 0
pg_stat_database_conflicts_confl_snapshot{datid="5",datname="postgres",server="localhost:5432"} 0
# HELP pg_stat_database_conflicts_confl_tablespace Number of queries in this database that have been canceled due to dropped tablespaces
# TYPE pg_stat_database_conflicts_confl_tablespace counter
pg_stat_database_conflicts_confl_tablespace{datid="1",datname="template1",server="localhost:5432"} 0
pg_stat_database_conflicts_confl_tablespace{datid="16384",datname="dev",server="localhost:5432"} 0
pg_stat_database_conflicts_confl_tablespace{datid="4",datname="template0",server="localhost:5432"} 0
pg_stat_database_conflicts_confl_tablespace{datid="5",datname="postgres",server="localhost:5432"} 0
```

**Comment by Sticksman** [comment]
Ok, interesting. We're only getting metrics from this: https://github.com/prometheus-community/postgres_exporter/blob/716ac23f202f664845d04c0d7b07000feae19c59/cmd/postgres_exporter/postgres_exporter.go#L166

This means that pg_stat_database metrics from this [collector](https://github.com/prometheus-community/postgres_exporter/blob/716ac23f202f664845d04c0d7b07000feae19c59/collector/pg_stat_database.go#L25) aren't being emitted at all.

**Comment by Sticksman** [comment]
It feels like something super dumb, like somehow a label name and a namespace are colliding

**Comment by sysadmind** [comment]
I have a feeling that it has something to do with a NULL column. Can someone try with log level turned up to debug and post the logs?

**Comment by algchoo** [comment]
Here's what I'm getting with the log level turned up to `debug`. I see some messages around columns being discarded due to version incompatibility and then below that I don't ever see the namespace `pg_stat_database` being queried, granted I'm assuming that is expected, not sure. Hope this helps!
```
ts=2023-07-27T12:32:18.712Z caller=server.go:74 level=info msg="Established new database connection" fingerprint=localhost:5432
ts=2023-07-27T12:32:18.727Z caller=postgres_exporter.go:594 level=debug msg="Querying PostgreSQL version" server=localhost:5432
ts=2023-07-27T12:32:18.727Z caller=postgres_exporter.go:622 level=info msg="Semantic version changed" server=localhost:5432 from=0.0.0 to=15.3.0
ts=2023-07-27T12:32:18.727Z caller=postgres_exporter.go:296 level=debug msg="Column is being forced to discard due to version incompatibility" column=flush_location
ts=2023-07-27T12:32:18.727Z caller=postgres_exporter.go:296 level=debug msg="Column is being forced to discard due to version incompatibility" column=sent_location
ts=2023-07-27T12:32:18.728Z caller=postgres_exporter.go:296 level=debug msg="Column is being forced to discard due to version incompatibility" column=pg_xlog_location_diff
ts=2023-07-27T12:32:18.728Z caller=postgres_exporter.go:296 level=debug msg="Column is being forced to discard due to version incompatibility" column=write_location
ts=2023-07-27T12:32:18.728Z caller=postgres_exporter.go:296 level=debug msg="Column is being forced to discard due to version incompatibility" column=procpid
ts=2023-07-27T12:32:18.728Z caller=postgres_exporter.go:296 level=debug msg="Column is being forced to discard due to version incompatibility" column=replay_location
ts=2023-07-27T12:32:18.728Z caller=pg_setting.go:35 level=debug msg="Querying pg_setting view" server=localhost:5432
ts=2023-07-27T12:32:18.728Z caller=postgres_exporter.go:594 level=debug msg="Querying PostgreSQL version" server=localhost:5432
ts=2023-07-27T12:32:18.734Z caller=namespace.go:193 level=debug msg="Querying namespace" namespace=pg_stat_database_conflicts
ts=2023-07-27T12:32:18.734Z caller=pg_setting.go:35 level=debug msg="Querying pg_setting view" server=localhost:5432
ts=2023-07-27T12:32:18.735Z caller=namespace.go:193 level=debug msg="Querying namespace" namespace=pg_locks
ts=2023-07-27T12:32:18.745Z caller=namespace.go:193 level=debug msg="Querying namespace" namespace=pg_stat_archiver
ts=2023-07-27T12:32:18.746Z caller=namespace.go:193 level=debug msg="Querying namespace" namespace=pg_stat_replication
ts=2023-07-27T12:32:18.747Z caller=namespace.go:193 level=debug msg="Querying namespace" namespace=pg_stat_activity
ts=2023-07-27T12:32:18.750Z caller=namespace.go:193 level=debug msg="Querying namespace" namespace=pg_replication_slots
ts=2023-07-27T12:32:18.757Z caller=namespace.go:193 level=debug msg="Querying namespace" namespace=pg_stat_database_conflicts
ts=2023-07-27T12:32:18.759Z caller=namespace.go:193 level=debug msg="Querying namespace" namespace=pg_stat_archiver
ts=2023-07-27T12:32:18.759Z caller=namespace.go:193 level=debug msg="Querying namespace" namespace=pg_locks
ts=2023-07-27T12:32:18.760Z caller=namespace.go:193 level=debug msg="Querying namespace" namespace=pg_stat_activity
ts=2023-07-27T12:32:18.762Z caller=namespace.go:193 level=debug msg="Querying namespace" namespace=pg_stat_replication
ts=2023-07-27T12:32:18.765Z caller=namespace.go:193 level=debug msg="Querying namespace" namespace=pg_replication_slots
```

**Comment by Sticksman** [comment]
Hm, I would have expected it to be registered at least.

**Comment by Sticksman** [comment]
Just ran a docker container with postgres 14 and a built v0.13.2. I'm seeing stat_database metrics get emitted:
``` HELP pg_stat_database_tup_deleted Number of rows deleted by queries in this database
# TYPE pg_stat_database_tup_deleted counter
pg_stat_database_tup_deleted{datid="0",datname="unknown"} 0
pg_stat_database_tup_deleted{datid="1",datname="template1"} 0
pg_stat_database_tup_deleted{datid="13779",datname="template0"} 0
pg_stat_database_tup_deleted{datid="13780",datname="postgres"} 0
pg_stat_database_tup_deleted{datid="16384",datname="circle_test"} 0
# HELP pg_stat_database_tup_fetched Number of rows fetched by queries in this database
# TYPE pg_stat_database_tup_fetched counter
pg_stat_database_tup_fetched{datid="0",datname="unknown"} 17
pg_stat_database_tup_fetched{datid="1",datname="template1"} 0
pg_stat_database_tup_fetched{datid="13779",datname="template0"} 0
pg_stat_database_tup_fetched{datid="13780",datname="postgres"} 816
pg_stat_database_tup_fetched{datid="16384",datname="circle_test"} 1198
# HELP pg_stat_database_tup_inserted Number of rows inserted by queries in this database
# TYPE pg_stat_database_tup_inserted counter
pg_stat_database_tup_inserted{datid="0",datname="unknown"} 1
pg_stat_database_tup_inserted{datid="1",datname="template1"} 0
pg_stat_database_tup_inserted{datid="13779",datname="template0"} 0
pg_stat_database_tup_inserted{datid="13780",datname="postgres"} 0
pg_stat_database_tup_inserted{datid="16384",datname="circle_test"} 0
# HELP pg_stat_database_tup_returned Number of rows returned by queries in this database
# TYPE pg_stat_database_tup_returned counter
pg_stat_database_tup_returned{datid="0",datname="unknown"} 32
pg_stat_database_tup_returned{datid="1",datname="template1"} 0
pg_stat_database_tup_returned{datid="13779",datname="template0"} 0
pg_stat_database_tup_returned{datid="13780",datname="postgres"} 897
pg_stat_database_tup_returned{datid="16384",datname="circle_test"} 1684
# HELP pg_stat_database_tup_updated Number of rows updated by queries in this database
# TYPE pg_stat_database_tup_updated counter
pg_stat_database_tup_updated{datid="0",datname="unknown"} 0
pg_stat_database_tup_updated{datid="1",datname="template1"} 0
pg_stat_database_tup_updated{datid="13779",datname="template0"} 0
pg_stat_database_tup_updated{datid="13780",datname="postgres"} 0
pg_stat_database_tup_updated{datid="16384",datname="circle_test"} 0```

**Comment by Sticksman** [comment]
However I do see that in the newest build we might skip some metrics due to the stats_reset column being null which we should account for.

**Comment by Sticksman** [comment]
> The debug logs do show the problem. I don't know why your logs don't include it. I spun up postgres locally with the exporter log level set to debug and I have these logs:

This is only in the latest build, not 0.13.2 which is what our @algchoo is running. I'm unclear what the issue with 0.13.2 is since it doesn't yet have the code skipping the metrics yet.

**Comment by algchoo** [comment]
The testing I've done has been against containers in k8s, rather than a local docker setup. Using `docker-compose`  I'm still running into the same problems. 

I'm running Docker Desktop 4.20.1 on MacOS 13.0.1 with an M1 chip and below is what I'm deploying. Is there anything wrong with this, perhaps? 
```yaml
version: "3.9"
services:
  postgres:
    restart: always
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=dev
  exporter:
    restart: always
    image: quay.io/prometheuscommunity/postgres-exporter:v0.13.0
    ports: 
      - 9187:9187
    environment:
      - DATA_SOURCE_NAME=postgresql://root:password@postgres:5432/dev?sslmode=disable
    command: --collector.stat_statements --log.level=debug
```

**Comment by Sticksman** [comment]
that all looks right. Let me run your docker-compose file and see if I can repro

**Comment by Sticksman** [comment]
@algchoo try with `quay.io/prometheuscommunity/postgres-exporter:v0.13.2` I believe that should fix the problem

**Comment by algchoo** [comment]
PostgreSQL 14 with exporter version `0.13.2` using `docker-compose`
```
CONTAINER ID   IMAGE                                                   COMMAND                  CREATED         STATUS         PORTS                    NAMES
9f109a7ae4f0   postgres:14                                             "docker-entrypoint.s…"   3 seconds ago   Up 2 seconds   0.0.0.0:5432->5432/tcp   postgresql-postgres-1
9eee314cf561   quay.io/prometheuscommunity/postgres-exporter:v0.13.2   "/bin/postgres_expor…"   3 seconds ago   Up 2 seconds   0.0.0.0:9187->9187/tcp   postgresql-exporter-1
❯ docker logs -f 9eee314cf561
ts=2023-07-28T22:16:31.824Z caller=main.go:86 level=warn msg="Error loading config" err="Error opening config file \"postgres_exporter.yml\": open postgres_exporter.yml: no such file or directory"
ts=2023-07-28T22:16:31.824Z caller=proc.go:250 msg="Excluded databases" databases=[]
ts=2023-07-28T22:16:31.825Z caller=main.go:142 level=warn msg="Failed to create PostgresCollector" err="dial tcp 172.18.0.3:5432: connect: connection refused"
ts=2023-07-28T22:16:31.826Z caller=tls_config.go:274 level=info msg="Listening on" address=[::]:9187
ts=2023-07-28T22:16:31.826Z caller=tls_config.go:277 level=info msg="TLS is disabled." http2=false address=[::]:9187
9ts=2023-07-28T22:17:00.325Z caller=server.go:74 level=info msg="Established new database connection" fingerprint=postgres:5432
ts=2023-07-28T22:17:00.344Z caller=postgres_exporter.go:594 level=debug msg="Querying PostgreSQL version" server=postgres:5432
ts=2023-07-28T22:17:00.346Z caller=postgres_exporter.go:622 level=info msg="Semantic version changed" server=postgres:5432 from=0.0.0 to=14.8.0
ts=2023-07-28T22:17:00.346Z caller=postgres_exporter.go:296 level=debug msg="Column is being forced to discard due to version incompatibility" column=replay_location
ts=2023-07-28T22:17:00.346Z caller=postgres_exporter.go:296 level=debug msg="Column is being forced to discard due to version incompatibility" column=procpid
ts=2023-07-28T22:17:00.346Z caller=postgres_exporter.go:296 level=debug msg="Column is being forced to discard due to version incompatibility" column=flush_location
ts=2023-07-28T22:17:00.346Z caller=postgres_exporter.go:296 level=debug msg="Column is being forced to discard due to version incompatibility" column=sent_location
ts=2023-07-28T22:17:00.346Z caller=postgres_exporter.go:296 level=debug msg="Column is being forced to discard due to version incompatibility" column=pg_xlog_location_diff
ts=2023-07-28T22:17:00.346Z caller=postgres_exporter.go:296 level=debug msg="Column is being forced to discard due to version incompatibility" column=write_location
ts=2023-07-28T22:17:00.346Z caller=pg_setting.go:35 level=debug msg="Querying pg_setting view" server=postgres:5432
ts=2023-07-28T22:17:00.351Z caller=namespace.go:193 level=debug msg="Querying namespace" namespace=pg_stat_replication
ts=2023-07-28T22:17:00.354Z caller=namespace.go:193 level=debug msg="Querying namespace" namespace=pg_replication_slots
ts=2023-07-28T22:17:00.355Z caller=namespace.go:193 level=debug msg="Querying namespace" namespace=pg_stat_archiver
ts=2023-07-28T22:17:00.367Z caller=namespace.go:193 level=debug msg="Querying namespace" namespace=pg_stat_activity
ts=2023-07-28T22:17:00.369Z caller=namespace.go:193 level=debug msg="Querying namespace" namespace=pg_stat_database_conflicts
ts=2023-07-28T22:17:00.370Z caller=namespace.go:193 level=debug msg="Querying namespace" namespace=pg_locks
ts=2023-07-28T22:20:23.544Z caller=postgres_exporter.go:594 level=debug msg="Querying PostgreSQL version" server=postgres:5432
ts=2023-07-28T22:20:23.544Z caller=pg_setting.go:35 level=debug msg="Querying pg_setting view" server=postgres:5432
ts=2023-07-28T22:20:23.550Z caller=namespace.go:193 level=debug msg="Querying namespace" namespace=pg_replication_slots
ts=2023-07-28T22:20:23.553Z caller=namespace.go:193 level=debug msg="Querying namespace" namespace=pg_stat_archiver
ts=2023-07-28T22:20:23.565Z caller=namespace.go:193 level=debug msg="Querying namespace" namespace=pg_stat_activity
ts=2023-07-28T22:20:23.568Z caller=namespace.go:193 level=debug msg="Querying namespace" namespace=pg_stat_database_conflicts
ts=2023-07-28T22:20:23.569Z caller=namespace.go:193 level=debug msg="Querying namespace" namespace=pg_locks
ts=2023-07-28T22:20:23.571Z caller=namespace.go:193 level=debug msg="Querying namespace" namespace=pg_stat_replication
```

PostgreSQL 15.3 with exporter `0.13.2` using `docker-compose`
```
CONTAINER ID   IMAGE                                                   COMMAND                  CREATED          STATUS          PORTS                    NAMES
acce6d2c4c14   postgres:15.3                                           "docker-entrypoint.s…"   11 seconds ago   Up 10 seconds   0.0.0.0:5432->5432/tcp   postgresql-postgres-1
9d95359eed3d   quay.io/prometheuscommunity/postgres-exporter:v0.13.2   "/bin/postgres_expor…"   11 seconds ago   Up 10 seconds   0.0.0.0:9187->9187/tcp   postgresql-exporter-1
❯ docker logs -f 9d95359eed3d
ts=2023-07-28T22:22:57.807Z caller=main.go:86 level=warn msg="Error loading config" err="Error opening config file \"postgres_exporter.yml\": open postgres_exporter.yml: no such file or directory"
ts=2023-07-28T22:22:57.807Z caller=proc.go:250 msg="Excluded databases" databases=[]
ts=2023-07-28T22:22:57.812Z caller=main.go:142 level=warn msg="Failed to create PostgresCollector" err="dial tcp 172.19.0.3:5432: connect: connection refused"
ts=2023-07-28T22:22:57.812Z caller=tls_config.go:274 level=info msg="Listening on" address=[::]:9187
ts=2023-07-28T22:22:57.812Z caller=tls_config.go:277 level=info msg="TLS is disabled." http2=false address=[::]:9187
ts=2023-07-28T22:23:15.861Z caller=server.go:74 level=info msg="Established new database connection" fingerprint=postgres:5432
ts=2023-07-28T22:23:15.879Z caller=postgres_exporter.go:594 level=debug msg="Querying PostgreSQL version" server=postgres:5432
ts=2023-07-28T22:23:15.880Z caller=postgres_exporter.go:622 level=info msg="Semantic version changed" server=postgres:5432 from=0.0.0 to=15.3.0
ts=2023-07-28T22:23:15.880Z caller=postgres_exporter.go:296 level=debug msg="Column is being forced to discard due to version incompatibility" column=procpid
ts=2023-07-28T22:23:15.880Z caller=postgres_exporter.go:296 level=debug msg="Column is being forced to discard due to version incompatibility" column=replay_location
ts=2023-07-28T22:23:15.880Z caller=postgres_exporter.go:296 level=debug msg="Column is being forced to discard due to version incompatibility" column=sent_location
ts=2023-07-28T22:23:15.880Z caller=postgres_exporter.go:296 level=debug msg="Column is being forced to discard due to version incompatibility" column=write_location
ts=2023-07-28T22:23:15.880Z caller=postgres_exporter.go:296 level=debug msg="Column is being forced to discard due to version incompatibility" column=pg_xlog_location_diff
ts=2023-07-28T22:23:15.880Z caller=postgres_exporter.go:296 level=debug msg="Column is being forced to discard due to version incompatibility" column=flush_location
ts=2023-07-28T22:23:15.880Z caller=pg_setting.go:35 level=debug msg="Querying pg_setting view" server=postgres:5432
ts=2023-07-28T22:23:15.882Z caller=namespace.go:193 level=debug msg="Querying namespace" namespace=pg_stat_database_conflicts
ts=2023-07-28T22:23:15.882Z caller=namespace.go:193 level=debug msg="Querying namespace" namespace=pg_locks
ts=2023-07-28T22:23:15.883Z caller=namespace.go:193 level=debug msg="Querying namespace" namespace=pg_stat_replication
ts=2023-07-28T22:23:15.885Z caller=namespace.go:193 level=debug msg="Querying namespace" namespace=pg_replication_slots
ts=2023-07-28T22:23:15.885Z caller=namespace.go:193 level=debug msg="Querying namespace" namespace=pg_stat_archiver
ts=2023-07-28T22:23:15.886Z caller=namespace.go:193 level=debug msg="Querying namespace" namespace=pg_stat_activity
ts=2023-07-28T22:23:26.921Z caller=postgres_exporter.go:594 level=debug msg="Querying PostgreSQL version" server=postgres:5432
ts=2023-07-28T22:23:26.922Z caller=pg_setting.go:35 level=debug msg="Querying pg_setting view" server=postgres:5432
ts=2023-07-28T22:23:26.932Z caller=namespace.go:193 level=debug msg="Querying namespace" namespace=pg_locks
ts=2023-07-28T22:23:26.933Z caller=namespace.go:193 level=debug msg="Querying namespace" namespace=pg_stat_replication
ts=2023-07-28T22:23:26.934Z caller=namespace.go:193 level=debug msg="Querying namespace" namespace=pg_replication_slots
ts=2023-07-28T22:23:26.934Z caller=namespace.go:193 level=debug msg="Querying namespace" namespace=pg_stat_archiver
ts=2023-07-28T22:23:26.934Z caller=namespace.go:193 level=debug msg="Querying namespace" namespace=pg_stat_activity
ts=2023-07-28T22:23:26.936Z caller=namespace.go:193 level=debug msg="Querying namespace" namespace=pg_stat_database_conflicts
```

Unfortunately, the results are the same for me with any version of the exporter `0.13.x` running against PostgreSQL 14/15. Is there anything specific around configuring PostgreSQL that I may be missing?

**Comment by Sticksman** [comment]
Did you try hitting the /metrics endpoint? Here's the docker-compose file I used 
```version: "3.9"
services:
  postgres:
    restart: always
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=dev
  exporter:
    restart: always
    image: quay.io/prometheuscommunity/postgres-exporter:v0.13.2
    ports:
      - 9187:9187
    environment:
      - DATA_SOURCE_NAME=postgresql://root:password@postgres:5432/dev?sslmode=disable
    command: --collector.stat_statements --log.level=debug
```

Here's a sample of the stats emitted ``` # HELP pg_stat_database_tup_deleted Number of rows deleted by queries in this database
# TYPE pg_stat_database_tup_deleted counter
pg_stat_database_tup_deleted{datid="0",datname="unknown"} 0
pg_stat_database_tup_deleted{datid="1",datname="template1"} 0
pg_stat_database_tup_deleted{datid="13779",datname="template0"} 0
pg_stat_database_tup_deleted{datid="13780",datname="postgres"} 0
pg_stat_database_tup_deleted{datid="16384",datname="dev"} 0
# HELP pg_stat_database_tup_fetched Number of rows fetched by queries in this database
# TYPE pg_stat_database_tup_fetched counter
pg_stat_database_tup_fetched{datid="0",datname="unknown"} 18
pg_stat_database_tup_fetched{datid="1",datname="template1"} 0
pg_stat_database_tup_fetched{datid="13779",datname="template0"} 0
pg_stat_database_tup_fetched{datid="13780",datname="postgres"} 1481
pg_stat_database_tup_fetched{datid="16384",datname="dev"} 2207
# HELP pg_stat_database_tup_inserted Number of rows inserted by queries in this database
# TYPE pg_stat_database_tup_inserted counter
pg_stat_database_tup_inserted{datid="0",datname="unknown"} 1
pg_stat_database_tup_inserted{datid="1",datname="template1"} 0
pg_stat_database_tup_inserted{datid="13779",datname="template0"} 0
pg_stat_database_tup_inserted{datid="13780",datname="postgres"} 0
pg_stat_database_tup_inserted{datid="16384",datname="dev"} 0
# HELP pg_stat_database_tup_returned Number of rows returned by queries in this database
# TYPE pg_stat_database_tup_returned counter
pg_stat_database_tup_returned{datid="0",datname="unknown"} 97
pg_stat_database_tup_returned{datid="1",datname="template1"} 0
pg_stat_database_tup_returned{datid="13779",datname="template0"} 0
pg_stat_database_tup_returned{datid="13780",datname="postgres"} 2868
pg_stat_database_tup_returned{datid="16384",datname="dev"} 2367
# HELP pg_stat_database_tup_updated Number of rows updated by queries in this database
```

Here's the namespaces ```felixyuan-exporter-1  | ts=2023-07-28T22:13:32.066Z caller=postgres_exporter.go:622 level=info msg="Semantic version changed" server=postgres:5432 from=0.0.0 to=14.8.0
felixyuan-exporter-1  | ts=2023-07-28T22:13:32.066Z caller=postgres_exporter.go:296 level=debug msg="Column is being forced to discard due to version incompatibility" column=write_location
felixyuan-exporter-1  | ts=2023-07-28T22:13:32.066Z caller=postgres_exporter.go:296 level=debug msg="Column is being forced to discard due to version incompatibility" column=replay_location
felixyuan-exporter-1  | ts=2023-07-28T22:13:32.066Z caller=postgres_exporter.go:296 level=debug msg="Column is being forced to discard due to version incompatibility" column=pg_xlog_location_diff
felixyuan-exporter-1  | ts=2023-07-28T22:13:32.066Z caller=postgres_exporter.go:296 level=debug msg="Column is being forced to discard due to version incompatibility" column=flush_location
felixyuan-exporter-1  | ts=2023-07-28T22:13:32.066Z caller=postgres_exporter.go:296 level=debug msg="Column is being forced to discard due to version incompatibility" column=procpid
felixyuan-exporter-1  | ts=2023-07-28T22:13:32.066Z caller=postgres_exporter.go:296 level=debug msg="Column is being forced to discard due to version incompatibility" column=sent_location
felixyuan-exporter-1  | ts=2023-07-28T22:13:32.066Z caller=pg_setting.go:35 level=debug msg="Querying pg_setting view" server=postgres:5432
felixyuan-exporter-1  | ts=2023-07-28T22:13:32.068Z caller=collector.go:194 level=debug msg="collector succeeded" name=stat_user_tables duration_seconds=0.02105875
felixyuan-exporter-1  | ts=2023-07-28T22:13:32.069Z caller=namespace.go:193 level=debug msg="Querying namespace" namespace=pg_stat_archiver
felixyuan-exporter-1  | ts=2023-07-28T22:13:32.070Z caller=collector.go:194 level=debug msg="collector succeeded" name=stat_database duration_seconds=0.022516792
felixyuan-exporter-1  | ts=2023-07-28T22:13:32.070Z caller=namespace.go:193 level=debug msg="Querying namespace" namespace=pg_stat_activity
felixyuan-exporter-1  | ts=2023-07-28T22:13:32.070Z caller=collector.go:194 level=debug msg="collector succeeded" name=replication duration_seconds=0.023129291
felixyuan-exporter-1  | ts=2023-07-28T22:13:32.072Z caller=collector.go:194 level=debug msg="collector succeeded" name=statio_user_tables duration_seconds=0.024922625
felixyuan-exporter-1  | ts=2023-07-28T22:13:32.073Z caller=namespace.go:193 level=debug msg="Querying namespace" namespace=pg_stat_database_conflicts
felixyuan-exporter-1  | ts=2023-07-28T22:13:32.073Z caller=namespace.go:193 level=debug msg="Querying namespace" namespace=pg_locks
felixyuan-exporter-1  | ts=2023-07-28T22:13:32.074Z caller=namespace.go:193 level=debug msg="Querying namespace" namespace=pg_stat_replication
felixyuan-exporter-1  | ts=2023-07-28T22:13:32.076Z caller=namespace.go:193 level=debug msg="Querying namespace" namespace=pg_replication_slots
felixyuan-exporter-1  | ts=2023-07-28T22:13:32.077Z caller=collector.go:194 level=debug msg="collector succeeded" name=database duration_seconds=0.029650667
```

One thing about the pg_stat_database collector in v0.13.x is that so far it was created without a logger, so that might be contributing to the lack of seeing it in the logs. There's a patch in master with a logger attached (and I should make sure all the other collectors have loggers)

**Comment by algchoo** [comment]
@Sticksman Yes, I hit the metrics endpoint and while I see output, I don't see the expected `pg_stat_database` metrics. The screenshot shared shows the results I'm getting when testing on any version of `0.13.x` against PG 14/15. I misunderstood how the logger was implemented, so if I were to build the exporter from `master` I'll have the logger that's attached to the `pg_stat_database` collector, correct? I think the best next step for me is to get actual log output and see what there is to see.
Screenshot 2023-07-31 at 9 37 04 AM

**Comment by Sticksman** [comment]
I think it'd probably be a decent next step. I'm going to try blowing away all my containers and seeing if there was a cache on my end that was causing me to show the metrics.

**Comment by Sticksman** [comment]
I've run into a rather strange situation: I've run your docker-compose file after pruning my containers and I can indeed reproduce the issue. However after going to run the two commands individually:
```
 docker run -p 5432:5432 -e POSTGRES_DB=dev -e POSTGRES_USER=root -e POSTGRES_PASSWORD=password -d postgres:14

docker run \                                                                                                 
  -p 9187:9187 \
  -e DATA_SOURCE_NAME="postgresql://root:password@172.17.0.2:5432/dev?sslmode=disable" \
  quay.io/prometheuscommunity/postgres-exporter:v0.13.2 --collector.stat_statements --log.level=debug
```

I'm finding no issues. Will try using the docker-compose file with the latest build to see if that changes anything.

**Comment by Sticksman** [comment]
@algchoo I added a `depends_on` to your yaml so it now looks like this:

```
  exporter:
    restart: always
    image: quay.io/prometheuscommunity/postgres-exporter:v0.13.2
    ports:
      - 9187:9187
    environment:
      - DATA_SOURCE_NAME=postgresql://root:password@postgres:5432/dev?sslmode=disable
    command: --collector.stat_statements --log.level=debug
    depends_on:
      - postgres
```

This fixed the issue and began allowing stat_database elements to correctly . This leads me to believe there's a race condition where starting the exporter before the db can cause collectors not to load. I'll file an issue.

**Comment by Sticksman** [comment]
@algchoo actually here's the error line in the logs 

`ts=2023-07-28T22:16:31.825Z caller=main.go:142 level=warn msg="Failed to create PostgresCollector" err="dial tcp 172.18.0.3:5432: connect: connection refused"`

**Comment by CarlosGitto** [comment]
Hi, I found the same bug some days ago. To fix it, I simply restart the containers, and then it works fine.

The command I used was `docker compose -f $COMPOSEFILE restart;`, where `$COMPOSEFILE` is the path to your Docker Compose file (e.g., ./docker/docker-compose.yml). 

This should help you get the service up and running again.
If you found a better solution please let me know!

**Comment by yasirsoleja** [comment]
Hello, it appears that as part of this change the `server` label was dropped from all `pg_stat_database` metrics. Was this intended? 

Currently working on upgrading from an older version and noted that the labels for `pg_stat_database` are no longer consistent with the labels for built-in metrics. Happy to adjust our configs if it was intentional, but just wanted to clarify as this was a breaking change not mentioned in the release notes.

**Pull request merged**
