### PR TITLE
Release v0.15.0

### PR DESCRIPTION
**Pull request by SuperQ**
* [ENHANCEMENT] Add 1kB and 2kB units #915
* [BUGFIX] Add error log when probe collector creation fails #918
* [BUGFIX] Fix test build failures on 32-bit arch #919
* [BUGFIX] Adjust collector to use separate connection per scrape #936

### CODE REVIEW

**Comment by SuperQ** [comment]
PG 10 was EoL 1 year ago.

https://www.postgresql.org/support/versioning/

**Review by sysadmind — APPROVED** [review]
LGTM. Is the policy that we will not intentionally break compat with V10 but without any guarantees?

**Comment by SuperQ** [comment]
Yea, that's the policy we've been sticking to. It's just good to remove old versions from the pipeline to not waste resources.

**Comment by roock** [comment]
@SuperQ Container images have been published on docker hub and quay.io, but I don't see the new version on the Github Release page. Will it be pushed there later or is/was there an error in the release process?

**Comment by SuperQ** [comment]
@roock Thanks for the reminder, I forgot to mark the draft release as published. Done.

**Pull request merged**
